// src/shared/type/ImageKey.ts

/**
 * loadAssets() と 必ず一致させる
 */
export const ImageKey = {
    // タイトル
    TITLE_TEXT: "TITLE_TEXT",
    // タイル
    DIRT: "DIRT",
    WOODS: "WOODS",
    PLAIN: "PLAIN",
    WOOD_FLOOR: "WOOD_FLOOR",
    SKY: "SKY",
    WALL: "WALL",
    YELLOW_WALL: "YELLOW_WALL",
    WATER: "WATER",
    DARK: "DARK",
    // 洞窟タイル
    CAVEWALL: "CAVEWALL",
    CAVEFLOOR: "CAVEFLOOR",
    // オブジェクト
    TREE: "TREE",
    THRONE: "THRONE",
    // キャラクター
    PLAYER_STAND_LEFT: "PLAYER_STAND_LEFT",
    PLAYER_STAND_RIGHT: "PLAYER_STAND_RIGHT",
    PLAYER_LEFT_0: "PLAYER_LEFT_0",
    PLAYER_LEFT_1: "PLAYER_LEFT_1",
    PLAYER_LEFT_2: "PLAYER_LEFT_2",
    PLAYER_RIGHT_0: "PLAYER_RIGHT_0",
    PLAYER_RIGHT_1: "PLAYER_RIGHT_1",
    PLAYER_RIGHT_2: "PLAYER_RIGHT_2",
    // ----- zone ------ // 
    // 侵入
    TOWN_ICON: "TOWN_ICON",
    CAVE: "CAVE",
    FOREST_TEMPLE: "FOREST_TEMPLE",
    // 敵
    ENEMY_ICON: "ENEMY_ICON",
    AREA_ICON: "AREA_ICON",
    // 看板
    WOODEN_SIGN: "WOODEN_SIGN",
    GOLD_ICON: "GOLD_ICON",
    POTION_ICON: "POTION_ICON",
    // NPC
    OMAENO_SHIWAZA_DATANO_KA: "OMAENO_SHIWAZA_DATANO_KA",
    // 背景
    BATTLE_BG_PLAIN: "BATTLE_BG_PLAIN",
    BATTLE_BG_FOREST: "BATTLE_BG_FOREST",
    BATTLE_BG_CAVE: "BATTLE_BG_CAVE",
    BATTLE_BG_DEEPER_CAVE: "BATTLE_BG_DEEPER_CAVE",
    BATTLE_BG_WATER: "BATTLE_BG_WATER",
    // 敵画像
    ENEMY1: "ENEMY1",
    ENEMY2: "ENEMY2",
    ENEMY3: "ENEMY3",
    ENEMY4: "ENEMY4",
    SP_DRACKY: "SP_DRACKY",
    SP_GHOST: "SP_GHOST",
    SP_SLIME: "SP_SLIME",
    SP_KILLER_LICKANT: "SP_KILLER_LICKANT",
    SP_METAL_SLIME: "SP_METAL_SLIME",
    // ステータスアイコン
    CHARM: "CHARM",
    POISON: "POISON",
    CONFUSION: "CONFUSION",
    PARALYSIS: "PARALYSIS",
    SLEEP: "SLEEP",
    STRONG_POISON: "STRONG_POISON",

} as const;
export type ImageKey = typeof ImageKey[keyof typeof ImageKey];
