// src/shared/type/screenTypes.ts

export const MainScreenType = {
    INIT_GAME_SCREEN: "INIT_GAME_SCREEN",
    TITLE: "TITLE",
    SLOT_SELECT: "SLOT_SELECT",
    START_MESSAGE: "START_MESSAGE",
    FOREST_TEMPLE: "FOREST_TEMPLE",
    WORLD_MAP: "WORLD_MAP",
    NO_FEATURE_TOWN: "NO_FEATURE_TOWN",
    GRAVE_CAVE: "GRAVE_CAVE",
    BATTLE_SCENE: "BATTLE_SCENE",
    BATTLE_ENEMY_SCREEN: "BATTLE_ENEMY_SCREEN",
    BATTLE_BACKGROUND_SCREEN: "BATTLE_BACKGROUND_SCREEN"
} as const;
export type MainScreenType = typeof MainScreenType[keyof typeof MainScreenType];

export const OverlayScreenType = {
    OPTIONS: "OPTIONS",
    INPUT_NAME_OVERLAY: "INPUT_NAME_OVERLAY",
    YES_NO_OVERLAY: "YES_NO_OVERLAY",
    INVENTORY: "INVENTORY",
    MESSAGE_LOG: "MESSAGE_LOG",
    BATTLE_BASIC_COMMAND_OVERLAY: "BATTLE_BASIC_COMMAND_OVERLAY",
    ATTACK_TARGET_OVERLAY: "ATTACK_TARGET_OVERLAY",
    MAGIC_TARGET_OVERLAY: "MAGIC_TARGET_OVERLAY",
    ITEM_SELECT_OVERLAY_IN_BATTLE: "ITEM_SELECT_OVERLAY_IN_BATTLE",
    BATTLE_LOG: "BATTLE_LOG",
} as const;
export type OverlayScreenType = typeof OverlayScreenType[keyof typeof OverlayScreenType];
