// src/shared/type/screenTypes.ts

export const MainScreenType = {
    INIT_GAME_SCREEN: "INIT_GAME_SCREEN",
    TITLE_SCENE: "TITLE_SCENE",
    SLOT_SELECT: "SLOT_SELECT",
    START_MESSAGE: "START_MESSAGE",
    FOREST_TEMPLE: "FOREST_TEMPLE",
    WORLD_MAP: "WORLD_MAP",
    NO_FEATURE_TOWN: "NO_FEATURE_TOWN",
    GRAVE_CAVE: "GRAVE_CAVE",
    BATTLE_SCENE: "BATTLE_SCENE",
    BATTLE_ENEMY_SCREEN: "BATTLE_ENEMY_SCREEN",
    BATTLE_BACKGROUND_SCREEN: "BATTLE_BACKGROUND_SCREEN"
} as const;
export type MainScreenType = typeof MainScreenType[keyof typeof MainScreenType];

export const OverlayScreenType = {
    OPTIONS: "OPTIONS",
    FIELD_COMMAND: "FIELD_COMMAND",
    SANDSTORM_OVERLAY: "SANDSTORM_OVERLAY",
    TITLE_OVERLAY: "TITLE_OVERLAY",
    SLOT_SELECT: "SLOTSELECT",
    INPUT_NAME_OVERLAY: "INPUT_NAME_OVERLAY",
    YES_NO_OVERLAY: "YES_NO_OVERLAY",
    INVENTORY: "INVENTORY",
    MESSAGE_LOG: "MESSAGE_LOG",
    BATTLE_BASIC_COMMAND_OVERLAY: "BATTLE_BASIC_COMMAND_OVERLAY",
    SELECT_TARGET_OVERLAY: "SELECT_TARGET_OVERLAY",
    SKILL_SELECT_OVERLAY: "SKILL_SELECT_OVERLAY",
    ITEM_SELECT_OVERLAY_IN_BATTLE: "ITEM_SELECT_OVERLAY_IN_BATTLE",
    BATTLE_LOG: "BATTLE_LOG",
    ALLIES_STATUS_OVERLAY: "ALLIES_STATUS_OVERLAY",
    BATTLE_TURN_DISPLAY: "BATTLE_TURN_DISPLAY",
    LEVEL_UP_OVERLAY: "LEVEL_UP_OVERLAY",
    SHOP: "SHOP"
} as const;
export type OverlayScreenType = typeof OverlayScreenType[keyof typeof OverlayScreenType];
